[tool.poetry]
name = "network-gcn"
version = "11"
description = "Graph Convolutions on Network Data"
authors = ["3lLobo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
determined = "^0.21.0"
torch = "^2.0.0"
torchvision = "^0.15.1"
torchaudio = "^2.0.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
