version: "3.9"

services:
  determined-db:
    image: docker.io/library/postgres:latest
    ports:
      - 5432:5432
    networks:
      - host
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: determined
      POSTGRES_USER: determined
      POSTGRES_DB: determined
    restart: unless-stopped

  determined-master:
    image: determinedai/determined-master:latest
    networks:
      - host
    ports:
      - 8080:8080
    # volumes:
    #   - ./master.yaml:/etc/determined/master.yaml
    #   - ./certs:/etc/determined/certs
    environment:
      DET_DB_HOST: determined-db
      DET_DB_PORT: 5432
      DET_DB_USER: determined
      DET_DB_PASSWORD: determined
      DET_DB_NAME: determined
      DET_DB_SSL_MODE: disable
    restart: unless-stopped

  determined-agent:
    image: determinedai/determined-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - host
    environment:
      DET_MASTER_HOST: determined-master
      DET_MASTER_PORT: 8080
      DET_AGENT_ID: 0
      DET_USE_TLS: false
      DET_USE_MTLS: false
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  host:
    internal: true
